// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientApi.Data;

#nullable disable

namespace PatientApi.Migrations
{
    [DbContext(typeof(PatientApiDbContext))]
    partial class PatientApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PatientApi.Models.Patient", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<bool>("Active").HasColumnType("bit");
                b.Property<DateTime>("BirthDate").IsRequired().HasColumnType("datetime2");
                b.Property<string>("Gender").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.HasKey("Id");
                b.HasIndex("BirthDate").HasDatabaseName("IX_Patients_BirthDate");
                b.ToTable("Patients");

                b.OwnsOne("PatientApi.Models.PatientName", "Name", n =>
                {
                    n.Property<string>("Family").IsRequired().HasMaxLength(255).HasColumnName("Family").HasColumnType("nvarchar(255)");
                    n.Property<string>("Given").IsRequired().HasMaxLength(1000).HasColumnName("Given").HasColumnType("nvarchar(1000)");
                    n.Property<string>("Use").IsRequired().HasMaxLength(50).HasColumnName("Use").HasColumnType("nvarchar(50)");
                    n.WithOwner().HasForeignKey("Id");
                    n.HasKey("Id");
                });

                b.Navigation("Name").IsRequired();
            });
           
#pragma warning restore 612, 618
        }
    }
}
